# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 582ab9da432216e8e196be4fb2581812fc05a10e14faf3ae4faaf0b618c57eb0dab85467b7d2fcc100bfdedd166185a332654a94f83decad2abd89c612842804

test:
  secret_key_base: dca69aec556bf2782be8a5dee19ab41b154942407f66fd91215186ff35c44804d0c67f6d0aa435758b54dd32efbc5802396fc639714f6887cba933362852c55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
